#!/usr/bin/env python3
"""
RabbitMQ Nagios NRPE Health Check
Copyright (C) 2024  Nick Thuesen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import argparse
import shlex
import subprocess
import sys
import json
import re
import requests
import urllib3

if "check_output" not in dir(subprocess):
    def check_output(*popenargs, **kwargs):
        if 'stdout' in kwargs:
            raise ValueError('stdout argument not allowed, it will be overridden.')
        process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
        output, unused_err = process.communicate()
        retcode = process.poll()
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
            raise subprocess.CalledProcessError(retcode, cmd, output=output)
        return output

    subprocess.check_output = check_output


class RabbitCmdWrapper(object):
    """
    Basically, this class just runs rabbitmqctl commands and returns parsed output.
       Typically this means you need root privs for this to work.
       Made this it's own class so it could be used in other monitoring tools
       if desired.
    """

    @classmethod
    def list_connections(cls):
        args = shlex.split("sudo rabbitmqctl list_connections")
        cmd_result = subprocess.check_output(args).strip()
        results = cls._parse_list_results(cmd_result)
        return results

    @classmethod
    def list_queues(cls):
        args = shlex.split('sudo rabbitmqctl list_queues -q')
        cmd_result = subprocess.check_output(args).strip()
        results = cls._parse_list_results(cmd_result)
        return results

    @classmethod
    def status(cls):
        args = shlex.split('sudo rabbitmqctl status')
        cmd_result = subprocess.check_output(args).strip()
        results = cls._parse_list_results(cmd_result)
        return results

    @classmethod
    def _parse_list_results(cls, result_string):
        results = result_string.strip().split('\n')
        # remove text fluff
        if "Listing connections ..." in results: results.remove("Listing connections ...")
        if "Listing queues ..." in results: results.remove("Listing queues ...")
        return_data = []
        for row in results:
            return_data.append(row.split('\t'))
        return return_data


def threshold_sanity(critical, warning):
    """Make sure we use both thresholds, not just one"""
    if warning and not critical:
        print("UNKNOWN - Define both thresholds, not just warning")
        sys.exit(3)
    elif critical and not warning:
        print("UNKNOWN - Define both thresholds, not just critical")


def check_connection_count(critical=0, warning=0):
    """Checks to make sure the numbers of connections are within parameters."""
    try:
        count = len(RabbitCmdWrapper.list_connections())
        if (critical and warning):
            if count >= critical:
                print(f"CRITICAL - Connection Count {count}|connections={count};{warning};{critical};0;;")
                sys.exit(2)
            elif count >= warning:
                print(f"WARNING - Connection Count {count}|connections={count};{warning};{critical};0;;")
                sys.exit(1)
            else:
                print(f"OK - Connection Count {count}|connections={count};{warning};{critical};0;;")
        else:
            print(f"OK - Connection Count {count}")
    except Exception as err:
        print(f"CRITICAL - {err}")


def check_queues_count(critical=1000, warning=1000):
    """
    A blanket check to make sure all queues are within count parameters.
    TODO: Possibly break this out so test can be done on individual queues.
    """
    try:
        critical_q = []
        warning_q = []
        results = RabbitCmdWrapper.list_queues()
        for queue in results:
            if len(queue) == 2:
                count = int(queue[1])
                if count >= critical:
                    critical_q.append("%s: %s" % (queue[0], count))
                elif count >= warning:
                    warning_q.append("%s: %s" % (queue[0], count))
        if critical_q:
            print(f"CRITICAL - {critical_q}")
            sys.exit(2)
        elif warning_q:
            print(f"WARNING - {warning_q}")
            sys.exit(1)
        else:
            print("OK - NO QUEUES EXCEED THRESHOLDS")
            sys.exit(0)
    except Exception as err:
        print(f"CRITICAL - {err}")
        sys.exit(2)


def check_mem_usage(critical=75, warning=50):
    """Check to make sure the RAM usage of rabbitmq process does not exceed 50%% of its max"""
    try:
        results = RabbitCmdWrapper.status()
        for line in results:
            rss = re.search(r'rss,([0-9]+)', str(line))
            vml = re.search(r'vm_memory_limit,([0-9]+)', str(line))
            if rss:
                memory_used = int(rss.groups()[0]) / 1024
            if vml:
                memory_limit = int(vml.groups()[0]) / 1024

        percent_usage = int(100 * memory_used / memory_limit)

        if percent_usage > critical:
            print(f"CRITICAL - RABBITMQ RAM USAGE at {percent_usage}% of max|TOTAL={memory_limit}KB;;;; USED={memory_used}KB;;;;")
            sys.exit(2)
        elif percent_usage > warning:
            print(f"WARNING - RABBITMQ RAM USAGE at {percent_usage}% of max|TOTAL={memory_limit}KB;;;; USED={memory_used}KB;;;;")
            sys.exit(1)
        else:
            print(f"OK - RABBITMQ RAM USAGE at {percent_usage}% of max|TOTAL={memory_limit}KB;;;; USED={memory_used}KB;;;;")

    except Exception as err:
        print(f"Critical - {err}")
        sys.exit(2)


def check_aliveness(username, password, timeout, cluster, port, ssl, certificate_verify):
    """
    Declares a test queue, then publishes and consumes a message.
    Intended for use by monitoring tools.
    If everything is working correctly, will return HTTP status 200 with body
    """
    try:
        protocol = "https" if ssl else "http"
        url = f"{protocol}://{cluster}:{port}/api/aliveness-test/%2F"
        r = requests.get(url, auth=(username, password), timeout=timeout, verify=certificate_verify)
    except requests.exceptions.RequestException as e:  # Throw error if rabbitmq is down
        print(f"Critical - {e}")
        sys.exit(2)
    if r.status_code == 200:
        print(f"OK - RABBITMQ Aliveness Test Returns: {r}")
        sys.exit(0)
    elif r.status_code != 200:
        print(f"CRITICAL - RabbitMQ Error: {r.content}")
        sys.exit(2)
    else:
        print("UNKNOWN - RABBITMQ Aliveness Test")
        sys.exit(1)


def check_cluster(username, password, timeout, cluster, port, ssl, certificate_verify):
    """Checks the health of a cluster, if a node is not running mark as offline"""
    urllib3.disable_warnings()
    try:
        protocol = "https" if ssl else "http"
        url = f"{protocol}://{cluster}:{port}/api/nodes"
        
        r = requests.get(url, auth=(username, password), timeout=timeout, verify=certificate_verify)
        
        if r.status_code == 401:
            print("Critical - Not authorized: Check your username and password")
            sys.exit(2)
        elif r.status_code != 200:
            print(f"Critical - Unexpected response: {r.status_code} {r.text}")
            sys.exit(2)
        
        # Process the response if authorized
        text = r.text
        nodes = r.json()

        running_nodes = []
        failed_nodes = []
        for node in nodes:
            if not node['running']:
                failed_nodes.append(node['name'])
            if node['running']:
                running_nodes.append(node['name'])

        if len(failed_nodes) == 1:
            print(f"WARNING: RabbitMQ cluster is degraded: Not running {failed_nodes[0]}")
            sys.exit(1)
        elif len(failed_nodes) >= 2:
            print(f"CRITICAL: RabbitMQ cluster is critical: Not running {failed_nodes}")
            sys.exit(2)
        else:
            print(f"OK: RabbitMQ cluster members: {' '.join(running_nodes)}")
    except requests.exceptions.RequestException as e:  # Throw error if no response
        print(f"Critical - {e}")
        sys.exit(2)


USAGE = """Usage: ./check_rabbitmq -c [ipaddress or fqdn] --port [port] -a [action] -C [critical] -W [warning]
           Actions:
           - connection_count
             checks the number of connection in rabbitmq's list_connections
           - queues_count
             checks the count in each of the queues in rabbitmq's list_queues
           - mem_usage
             checks to ensure mem usage of rabbitmq process does not exceed 50%
           - aliveness
             Use the /api/aliveness-test API to send/receive a message. (requires -u username -p password args)
           - cluster_status
             Parse /api/nodes to check the cluster status. (requires -u username -p password)"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Check RabbitMQ cluster status", usage=USAGE)
    parser.add_argument("-a", "--action", required=True, help="Action to Check")
    parser.add_argument("-C", "--critical", type=int, help="Critical Threshold")
    parser.add_argument("-W", "--warning", type=int, help="Warning Threshold")
    parser.add_argument("-u", "--username", default="guest", type=str, help="RabbitMQ username, Default guest")
    parser.add_argument("-p", "--password", default="guest", type=str, help="RabbitMQ password, Default guest")
    parser.add_argument("-t", "--timeout", default=1, type=int, help="Request Timeout, defaults to 1 second")
    parser.add_argument("-c", "--cluster", default="localhost", type=str, help="Cluster IP/DNS name, defaults to localhost")
    parser.add_argument("--port", default="15672", type=str, help="Cluster port, defaults to 15672")
    parser.add_argument("--ssl", default=True, type=bool, help="Pass to use https")
    parser.add_argument("--ignore-ssl-certificate", dest="certificate_verify", default=False, type=bool, help="Bypass SSL Certification verification")

    options = parser.parse_args()

    if options.action == "connection_count":
        threshold_sanity(options.critical, options.warning)
        check_connection_count(options.critical, options.warning)
    elif options.action == "queues_count":
        check_queues_count(options.critical, options.warning)
    elif options.action == "mem_usage":
        check_mem_usage(options.critical, options.warning)
    elif options.action == "aliveness":
        check_aliveness(options.username, options.password, options.timeout, options.cluster, options.port, options.ssl, options.certificate_verify)
    elif options.action == "cluster_status":
        check_cluster(options.username, options.password, options.timeout, options.cluster, options.port, options.ssl, options.certificate_verify)
    else:
        print(f"Invalid action: {options.action}")
        print(USAGE)
        sys.exit(1)
